carts/urls.py
from django.urls import path

from . import views


urlpatterns = [
  path('', views.cart, name='cart'),
  path('add_cart/<int:product_id>/', views.add_cart, name='add_cart'),
  path('remove_cart/<int:product_id>/<int:cart_item_id>/', views.remove_cart, name='remove_cart'),
  path('remove_cart_item/<int:product_id>/<int:cart_item_id>/', views.remove_cart_item, name='remove_cart_item'),
  path('checkout/', views.checkout, name='checkout'),
]

config/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name="home"),
    path('store/', include('store.urls')),
    path('cart/', include('carts.urls')),
    path('accounts/', include('accounts.urls'))    ,
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path

from . import views

urlpatterns = [
  path('', views.store, name="store"),
  path('category/<slug:category_slug>/', views.store, name="products_by_category_slug"),
  path('category/<slug:category_slug>/<slug:product_slug>/', views.product_detail, name="product_detail"),
  path('search/', views.search, name='search'),
]

carts/models.py
from django.db import models

from accounts.models import Account
from store.models import Category, Product, Variation
# Create your models here.

class Cart(models.Model):
  cart_id = models.CharField(max_length=255, blank=True)
  date_added = models.DateTimeField(auto_now_add=True)

  def __str__(self):
    return self.cart_id

class CartItem(models.Model):
  user = models.ForeignKey(Account, on_delete=models.CASCADE, null=True)
  product = models.ForeignKey(Product, on_delete=models.CASCADE)
  cart = models.ForeignKey(Cart, on_delete=models.CASCADE, null=True)
  quantity = models.IntegerField()
  is_active = models.BooleanField(default=True)
  variations = models.ManyToManyField(Variation, blank=True)

  def sub_total(self):
    return self.product.price * self.quantity

  def __str__(self):
    return str(self.product)
  

store/models.py
from django.db import models
from django.urls import reverse

from category.models import Category

# Create your models here.
class Product(models.Model):
  name          = models.CharField(max_length=200, unique=True)
  slug          = models.CharField(max_length=200, unique=True)
  description   = models.TextField(max_length=500, blank=True)
  price         = models.IntegerField()
  image         = models.ImageField(upload_to='photos/products', blank=True)
  stock         = models.IntegerField()
  is_available  = models.BooleanField(default=True)
  category      = models.ForeignKey(Category, on_delete=models.CASCADE)
  created_at    = models.DateTimeField(auto_now_add=True)
  modified_at   = models.DateTimeField(auto_now=True)

  def get_url(self):
    return reverse('product_detail', args=[self.category.slug, self.slug])

  def __str__(self):
    return self.name
  

class VariationManager(models.Manager):
  def colors(self):
    return super().filter(category='color', is_active=True)

  def sizes(self):
    return super().filter(category='size', is_active=True)


class Variation(models.Model):
  variation_category_choice = (
    ('color', 'color'),
    ('size', 'size'),
  )

  product = models.ForeignKey(Product, on_delete=models.CASCADE)
  category = models.CharField(max_length=100, choices=variation_category_choice) 
  value = models.CharField(max_length=100)
  is_active = models.BooleanField(default=True)
  created_at = models.DateTimeField(auto_now_add=True)

  objects = VariationManager()

  def __str__(self):
    return str(self.value)

carts/views.py
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import render, redirect, get_object_or_404

from store.models import Product, Variation

from . models import Cart, CartItem

# Create your views here.

from django.http import HttpResponse


def cart_id(request):
  cart = request.session.session_key
  if not cart:
    cart = request.session.create()
  return cart


def add_cart(request, product_id):

  product = Product.objects.get(id=product_id)
  current_user = request.user
  if current_user.is_authenticated:
    # if user is authenticated
    product_vars = []
    if request.method == 'POST':
      for var_category in request.POST:
        var_value = request.POST[var_category]
        try:
          variation = Variation.objects.get(
            product__id=product_id, 
            category__iexact=var_category, 
            value__iexact=var_value
          )
          product_vars.append(variation)
        except:
          pass

    cart_item = CartItem.objects.filter(product=product, user=current_user)
    if cart_item.exists():
      ex_var_list, ids = [], []
      for item in cart_item:
        ex_var_list.append(list(item.variations.all()))
        ids.append(item.id)
      
      if product_vars in ex_var_list:
        index = ex_var_list.index(product_vars)
        item_id = ids[index]
        item = CartItem.objects.get(product=product, id=item_id)
        item.quantity += 1
        item.save()
        
      else:
        item = CartItem.objects.create(product=product, quantity=1, user=current_user)
        if len(product_vars) > 0:
          item.variations.clear()
          item.variations.add(*product_vars)
        item.save()
    else:
      cart_item = CartItem.objects.create(product=product, quantity=1, user=current_user)
      if len(product_vars) > 0:
        cart_item.variations.clear()
        cart_item.variations.add(*product_vars)
      cart_item.save()
  else:
    product_vars = []
    if request.method == 'POST':
      for var_category in request.POST:
        var_value = request.POST[var_category]
        print(f"{var_category} + ' ' + {var_value}")

        try:
          variation = Variation.objects.get(
            product__id=product_id, 
            category__iexact=var_category, 
            value__iexact=var_value
          )
          product_vars.append(variation)
        except:
          pass
    try:
      cart = Cart.objects.get(cart_id=cart_id(request))
    except Cart.DoesNotExist as e:
      cart = Cart.objects.create(cart_id=cart_id(request))
      cart.save()

    cart_item_exists = CartItem.objects.filter(product=product, cart=cart).exists()
    if cart_item_exists:
      cart_item = CartItem.objects.filter(product=product, cart=cart)

      ex_var_list, ids = [], []
      for item in cart_item:
        ex_var_list.append(list(item.variations.all()))
        ids.append(item.id)
      
      if product_vars in ex_var_list:
        index = ex_var_list.index(product_vars)
        item_id = ids[index]
        item = CartItem.objects.get(product=product, id=item_id)
        item.quantity += 1
        item.save()
        
      else:
        item = CartItem.objects.create(product=product, quantity=1, cart=cart)
        if len(product_vars) > 0:
          item.variations.clear()
          item.variations.add(*product_vars)
        item.save()
    else:
      cart_item = CartItem.objects.create(product=product, quantity=1, cart=cart)
      if len(product_vars) > 0:
        cart_item.variations.clear()
        cart_item.variations.add(*product_vars)
      cart_item.save()

  return redirect('cart')


def cart(request, total=0, quantity=0, cart_items=None):
  try:
    tax = grand_total = 0
    if request.user.is_authenticated:
      cart_items = CartItem.objects.filter(user=request.user)
    else:
      cart = Cart.objects.get(cart_id=cart_id(request))
      cart_items = CartItem.objects.filter(cart=cart, is_active=True)
    for item in cart_items:
      total += item.product.price * item.quantity
      quantity += item.quantity
    tax = (2 / 100) * total
    grand_total = total + tax
  except ObjectDoesNotExist:
    pass

  context = { 
    'total': total, 
    'quantity': quantity, 
    'cart_items': cart_items, 
    'grand_total': grand_total,
    'tax': tax,
  }
  return render(request, 'store/cart.html', context)


def remove_cart(request, product_id, cart_item_id):
  product = get_object_or_404(Product, id=product_id)
  try:
    if request.user.is_authenticated:
      cart_item = CartItem.objects.get(product, user=request.user, id=cart_item_id)
    else:
      cart = Cart.objects.get(cart_id=cart_id(request))
      cart_item = CartItem.objects.get(cart=cart, product=product, id=cart_item_id)
    
    if cart_item.quantity <= 1:
      cart_item.delete()
    else:
      cart_item.quantity -= 1
      cart_item.save()
  except:
    pass  
  return redirect('cart')


def remove_cart_item(request, product_id, cart_item_id):
  product = get_object_or_404(Product, id=product_id)
  if request.user.is_authenticated:
    cart_item = CartItem.objects.get(user=request.user, product=product, id=cart_item_id)
  else:
    cart = Cart.objects.get(cart_id=cart_id(request))
    cart_item = CartItem.objects.get(cart=cart, product=product, id=cart_item_id)
  cart_item.delete()
  return redirect('cart')

@login_required(login_url='login')
def checkout(request, total=0, quantity=0, cart_items=None):
  try:
    tax = grand_total = 0
    cart = Cart.objects.get(cart_id=cart_id(request))
    cart_items = CartItem.objects.filter(cart=cart, is_active=True)
    for item in cart_items:
      total += item.product.price * item.quantity
      quantity += item.quantity
    tax = (2 / 100) * total
    grand_total = total + tax
  except ObjectDoesNotExist:
    pass

  context = { 
    'total': total, 
    'quantity': quantity, 
    'cart_items': cart_items, 
    'grand_total': grand_total,
    'tax': tax,
  }
  return render(request, 'store/checkout.html', context)

store/views.py
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.db.models import Q
from django.shortcuts import render, get_object_or_404

from carts.models import CartItem
from carts.views import cart_id

from .models import Product, Category


# Create your views here.

def store(request, category_slug=None):
  if category_slug != None:
    category = get_object_or_404(Category, slug=category_slug)
    products = Product.objects.filter(
      category=category, is_available=True).order_by('id')
    product_count = products.count()
  else:
    products = Product.objects.filter(is_available=True)
    product_count = products.count()
  
  paginator = Paginator(products, 6)
  page = request.GET.get('page')
  paged_products = paginator.get_page(page)

  context = {
      'products': paged_products,
      'product_count': product_count
  }
  return render(request, 'store/store.html', context)


def product_detail(request, category_slug, product_slug):
  try:
    product = Product.objects.get(category__slug=category_slug, slug=product_slug)
    in_cart = CartItem.objects.filter(cart__cart_id=cart_id(request), product=product).exists()
  except Exception as e:
    raise e
  
  context = { 'product' : product, 'in_cart': in_cart, }
  return render(request, 'store/product_detail.html', context)


def search(request):
  keyword = request.GET.get('keyword', None)
  if keyword:
    products = Product.objects.order_by('-created_at').filter(
      Q(description__icontains=keyword) | Q(name__icontains=keyword))
  context = {
      'products': products,
      'product_count': products.count()
  }
  return render(request, 'store/store.html', context=context)

templates/store/cart.html
{% extends 'base.html' %}

{% load static %}

{% block content %}



<section class="section-content padding-y bg">
  <div class="container">
  
  <!-- ============================ COMPONENT 1 ================================= -->
  
  
  {% if not cart_items %}

    <h2 class="text-center">Your shopping cart is empty</h2>
    <br>
    <div class="text-center">
      <a href="{% url 'store' %}" class="btn btn-primary">Continue Shopping</a>
    </div>
    
  {% else %}

  <div class="row">
    <aside class="col-lg-9">
  <div class="card">  
  <table class="table table-borderless table-shopping-cart">
  <thead class="text-muted">
  <tr class="small text-uppercase">
    <th scope="col">Product</th>
    <th scope="col" width="120">Quantity</th>
    <th scope="col" width="120">Price</th>
    <th scope="col" class="text-right" width="200"> </th>
  </tr>
  </thead>
  <tbody>
    
  {% for item in cart_items  %}
      
  <tr>
    <td>
      <figure class="itemside align-items-center">
        <div class="aside"><img src="{{ item.product.image.url }}" class="img-sm"></div>
        <figcaption class="info">
          <a href="{{ item.product.get_url }}" 
              class="title text-dark">
            {{ item.product.name }}
          </a>
          <p class="small text-muted">
            
            {% if item.variations.all %}
              
              {% for varn in item.variations.all %}
                {{ varn.category|capfirst }} : {{ varn.value|capfirst }}
              {% endfor %}
                
            {% endif %}
              
          </p>
        </figcaption>
      </figure>
    </td>
    <td> 
      <!-- col.// -->
            <div class="col"> 
              <div class="input-group input-spinner">
                <div class="input-group-prepend">
                <a href="{% url 'remove_cart' item.product.id item.id %}" class="btn btn-light" type="button" id="button-minus"> <i class="fa fa-minus"></i> </a>
                </div>
                <input type="text" class="form-control"  value="{{ item.quantity }}"> 
                <div class="input-group-append">
                  <form action="{% url 'add_cart' item.product.id %}" method="POST">
                    {% csrf_token %}
                    {% for varn in item.variations.all %}
                      <input type="hidden" name="{{ varn.category }}" value="{{ varn.value }}">
                    {% endfor %}
                      
                    <button type="submit" class="btn btn-light" type="button" id="button-plus"> 
                      <i class="fa fa-plus"></i> 
                    </button>
                  </form>
                </div>
              </div> <!-- input-group.// -->
            </div> <!-- col.// -->
    </td>
    <td> 
      <div class="price-wrap"> 
        <var class="price">$ {{ item.sub_total }}</var> 
        <small class="text-muted"> $ {{ item.product.price }} each</small> 
      </div> <!-- price-wrap .// -->
    </td>
    <td class="text-right"> 
      <a href="{% url 'remove_cart_item' item.product.id item.id%}" class="btn btn-danger"> Remove</a>
    </td>
  </tr>

  {% endfor %}
  </tbody>
  </table>
  </div> <!-- card.// -->
  
    </aside> <!-- col.// -->
    <aside class="col-lg-3">
  
      <div class="card">
      <div class="card-body">
        <dl class="dlist-align">
          <dt>Total price:</dt>
          <dd class="text-right">$ {{ total }}</dd>
        </dl>
        <dl class="dlist-align">
          <dt>Tax:</dt>
          <dd class="text-right"> $ {{ tax }}</dd>
        </dl>
        <dl class="dlist-align">
          <dt>Total:</dt>
          <dd class="text-right text-dark b"><strong>$ {{ grand_total }} </strong></dd>
        </dl>
        <hr>
        <p class="text-center mb-3">
          <img src="{% static './images/misc/payments.png' %}" height="26">
        </p>
        <a href="{% url 'checkout' %}" class="btn btn-primary btn-block"> Checkout </a>
        <a href="{% url 'store' %}" class="btn btn-light btn-block">Continue Shopping</a>
      </div> <!-- card-body.// -->
      </div> <!-- card.// -->
  
  </aside> <!-- col.// -->
  
  
  </div> <!-- row.// -->

    
  {% endif %}
  <!-- ============================ COMPONENT 1 END .// ================================= -->
  
  </div> <!-- container .//  -->
  </section>




{% endblock %}
  

templates/store/checkout.html
{% extends 'base.html' %}

{% load static %}

{% block content %}



<section class="section-content padding-y bg">
  <div class="container">
  
    <!-- ============================ COMPONENT 1 ================================= -->

    <div class="row">
      <form action="" method="POST">
        <div class="row">

          <aside class="col-lg-6">
            <div class="card">  
              <div class="card-body">
                <h4 class="card-title mb-4">Billing Address</h4>
                  <div class="form-row">
                    <div class="col form-group">
                      <label for="">First Name</label>
                      <input type="text" name="first_name" class="form-control" required>
                    </div>
                    <div class="col form-group">
                      <label for="">Last Name</label>
                      <input type="text" name="last_name" class="form-control" required>
                    </div>
                  </div>
                  <div class="form-row">
                    <div class="col form-group">
                      <label for="">Email</label>
                      <input type="email" name="email" class="form-control" required>
                    </div>
                    <div class="col form-group">
                      <label for="">Phone Number</label>
                      <input type="text" name="phone" class="form-control" required>
                    </div>
                  </div>
                  <div class="form-row">
                    <div class="col form-group">
                      <label for="">Address Line 1</label>
                      <input type="text" name="address_line_1" class="form-control" required>
                    </div>
                    <div class="col form-group">
                      <label for="">Address Line 2</label>
                      <input type="text" name="address_line_2" class="form-control">
                    </div>
                  </div>
                  <div class="form-row">
                    <div class="col form-group">
                      <label for="">City</label>
                      <input type="text" name="city" class="form-control" required>
                    </div>
                    <div class="col form-group">
                      <label for="">State</label>
                      <input type="text" name="state" class="form-control" required>
                    </div>
                    <div class="col form-group">
                      <label for="">Country</label>
                      <input type="text" name="country" class="form-control" required>
                    </div>
                  </div>
                  <div class="form-row">
                    <div class="col form-group">
                      <label for="">Order Note</label>
                      <textarea name="order_note" rows="2" class="form-control"></textarea>
                    </div>
                  </div>
              </div>
            </div> <!-- card.// -->
          </aside> <!-- col.// -->

          <aside class="col-lg-6">
            <div class="card">
              <div class="card-body">
          
                <table class="table table-borderless table-shopping-cart">
                <thead class="text-muted">
                <tr class="small text-uppercase">
                  <th scope="col">Product</th>
                  <th scope="col" width="120">Quantity</th>
                  <th scope="col" width="120">Price</th>
                </tr>
                </thead>
                <tbody>
                  
                {% for item in cart_items  %}
                    
                <tr>
                  <td>
                    <figure class="itemside align-items-center">
                      <div class="aside"><img src="{{ item.product.image.url }}" class="img-sm"></div>
                      <figcaption class="info">
                        <a href="{{ item.product.get_url }}" 
                            class="title text-dark">
                          {{ item.product.name }}
                        </a>
                        <p class="small text-muted">
                          
                          {% if item.variations.all %}
                            
                            {% for varn in item.variations.all %}
                              {{ varn.category | capfirst }} : {{ varn.value | capfirst }} <br>
                            {% endfor %}
                              
                          {% endif %}
                            
                        </p>
                      </figcaption>
                    </figure>
                  </td>
                  <td>
                    <label for="">{{ item.quantity }}</label>
                  </td>
                  <td> 
                    <div class="price-wrap"> 
                      <var class="price">$ {{ item.sub_total }}</var> 
                      <small class="text-muted"> $ {{ item.product.price }} each</small> 
                    </div> <!-- price-wrap .// -->
                  </td>
                </tr>
              
                {% endfor %}
                </tbody>
                </table>
                <button type="submit" class="btn btn-primary btn-block">Place Order</button>
                <a href="{% url 'store' %}" class="btn btn-light btn-block">Continue Shopping</a>
              
              </div> <!-- card-body.// -->
            </div> <!-- card.// -->
          </aside> <!-- col.// -->

        </div> <!-- row.//-->
      </form> <!-- form.// -->
    </div> <!-- row.// -->

    <!-- ============================ COMPONENT 1 END .// ================================= -->
    
  </div> <!-- container .//  -->
</section>

{% endblock %}
  

templates/store/product_detail.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
  
<section class="section-content padding-y bg">
  <div class="container">
  
  <!-- ============================ COMPONENT 1 ================================= -->
  <div class="card">
    <div class="row no-gutters">

      <aside class="col-md-6">
        <article class="gallery-wrap"> 
          <div class="img-big-wrap">
            <a href="#"><img src="{{ product.image.url }}"></a>
          </div> <!-- img-big-wrap.// -->
          
        </article> <!-- gallery-wrap .end// -->
      </aside>

      <main class="col-md-6 border-left">
        <form action="{% url 'add_cart' product.id %}" method="POST">

          {% csrf_token %}

          <article class="content-body">
          
          <h2 class="title">{{ product.name }}</h2>
          
          <div class="mb-3"> 
            <var class="price h4">$ {{ product.price }}</var> 
          </div>
          
          <p>{{ product.description }}</p>
          
          <hr>
            <div class="row">
              <div class="item-option-select">
                <h6>Choose Color</h6>
                <select name="color" class="form-control" required>
                  <option value="" disabled selected>Select</option>
                  
                  {% for color in product.variation_set.colors %}
                    <option value="{{ color.value|lower }}"> {{ color.value|capfirst }} </option>
                  {% endfor %}
                    
                </select>
              </div>
            </div> <!-- row.// -->
            <div class="row">
              <div class="item-option-select">
                <h6>Select Color</h6>
                <select name="size" class="form-control" required>
                  <option value="" disabled selected>Select</option>
                  
                  {% for size in product.variation_set.sizes %}
                    <option value="{{ size.value|lower }}"> {{ size.value|capfirst }} </option>
                  {% endfor %}

                </select>
              </div>
            </div> <!-- row.// -->
            <hr>
            
            {% if product.stock <= 0 %}
              <h5 class="text-danger">Out of stock</h5>
            {% else %}
              <button class="btn btn-primary" type=submit""> 
                <span class="text">Add to cart</span> <i class="fas fa-shopping-cart"></i>
              </button>
            {% endif %}
              
          </article> <!-- product-info-aside .// -->
        </form>
      </main> <!-- col.// -->
    </div> <!-- row.// -->
  </div> <!-- card.// -->
  <!-- ============================ COMPONENT 1 END .// ================================= -->
  
  <br>
  
  <div class="row">
        <div class="col-md-9">
  
    <header class="section-heading">
      <h3>Customer Reviews</h3>
    </header>
  
    <article class="box mb-3">
      <div class="icontext w-100">
        <img src="{% static './images/avatars/avatar1.jpg' %}"  class="img-xs icon rounded-circle">
        <div class="text">
          <span class="date text-muted float-md-right">24.04.2020 </span>  
          <h6 class="mb-1">Mike John </h6>
          
        </div>
      </div> <!-- icontext.// --> 
      <div class="mt-3">
        <p>
          Dummy comment Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
          tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
          quis nostrud exercitation ullamco laboris nisi ut aliquip
        </p>	
      </div>
    </article>
  
    
  
    </div> <!-- col.// -->
  </div> <!-- row.// -->
  
  
  </div> <!-- container .//  -->
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->

{% endblock content %}
  